require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

Lint/UselessAssignment:
  Exclude:
    - "**/*.slim*"

FactoryBot/AssociationStyle:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

FactoryBot/ConsistentParenthesesStyle:
  Enabled: false

FactoryBot/FactoryAssociationWithStrategy:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - app/admin/*

Rails/LexicallyScopedActionFilter:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9

AllCops:
  NewCops: enable
  Exclude:
    - '*.gemspec'
    - 'bin/**/*'
    - 'Capfile'
    - 'config.ru'
    - 'config/**/*'
    - 'db/**/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'lib/tasks/**/*'
    - 'node_modules/**/*'
    - 'Rakefile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'
